
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_CART_ITEM = 'SET_CART_ITEM'
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const LOG_OUT="LOG_OUT"
export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOAD_PROFILE="LOAD_PROFILE"